gpu_id: 0
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'expSVQAD-QA'

train:
  lr: 0.0001
  batch_size: 32
  restore: True
  max_epochs: 25
  word_dim: 300
  module_dim: 512
  glove: True
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 1

val:
  flag: True

test:
  test_num: 0
  write_preds: False

inference:
  device: 'cuda'
  num_clips: 8
  num_frames_per_clip: 16
  appr_image_height: 224
  appr_image_width: 224
  motion_image_height: 112
  motion_image_width: 112
  vocab_json: 'data/svqad/svqad-qa_vocab.json'
  ckpt_path: "results/expSVQAD-QA/ckpt/model.pt"

dataset:
  name: 'svqad-qa'
  question_type: 'none'
  data_dir: 'data/svqad-qa'
  save_dir: '/content/drive/MyDrive/DFColab/VideoQA/results/'